# Generated by Django 4.2.11 on 2024-07-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_coffee_description_remove_snack_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='description',
            field=models.TextField(default='Default Description'),
        ),
        migrations.AddField(
            model_name='snack',
            name='description',
            field=models.TextField(default='Default Description'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
